[ADD] 호스트페이지 숙소등록 및 USER 에게 HOST 권한 부여
wecode-bootcamp-korea/38-2nd-airB-backend pull request #13
Opened 2022-11-04 18:29 UTC by JeongDoYoung2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 호스트페이지 숙소등록 및 USER 에게 HOST 권한 부여

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 호스트페이지에서 유저(guest)가 숙소를 등록할 시 host 권한이 부여됨과 동시에 product 테이블에 숙소의 정보들이 기입됩니다.

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- transaction을 한번더 사용함으로써 로직을 파악하기 더 수월했습니다.
- 콜백함수를 보다 능숙하게 쓸 수 있게 되었습니다.

## :: 기타 질문 및 특이 사항
-트랜잭션을 적용한 이유가 guest가 숙소를등록하기 전에 host 권한이 부여되는 것을 방지하기 위함이었는데, 잘 사용한게 맞는지 궁금합니다.

2022-11-07 04:50 UTC, kyeongraekim requested changes

2022-11-07 04:50 UTC, kyeongraekim commented on controllers/hostController.js
> +    if( !title || !price || !latitude || !longitude || !description || !bed || !bedroom || !bathroom || !guestMax || !buildingTypeId || !cityId || !themeId || !hostDescription ){
해당 부분은 라인 브레이킹을 통해서 가독성을 더 높여주세요!~

2022-11-07 04:50 UTC, kyeongraekim commented on models/hostDao.js
> +    await queryRunner.startTransaction();
- 해당 queryRunner 또한 try-catch 문안에 넣어야 정상적으로 의도한 내용이 작동할 것 같네요!
- 하나의 패키지로서 전체 transaction 쿼리가 동작해야지 에러 발생의 변수가 줄어들 것 입니다.

2022-11-07 04:50 UTC, kyeongraekim commented on models/hostDao.js
> +		            host_id,
indentation 확인해주세요!~

2022-11-07 04:50 UTC, kyeongraekim commented on models/hostDao.js
> +                [ await authorizeHostByUserId( userId, hostDescription ), title, price, latitude, longitude, description, bed, bedroom, bathroom, guestMax, buildingTypeId, cityId, themeId ]
중간에 소괄호가 들어간 것으로 보이는데 정상 작동이 되던가요?

2022-11-07 16:24 UTC, JeongDoYoung2 commented on models/hostDao.js
> +                [ await authorizeHostByUserId( userId, hostDescription ), title, price, latitude, longitude, description, bed, bedroom, bathroom, guestMax, buildingTypeId, cityId, themeId ]
INSERT INTO 문을 닫아주는 소괄호라 정상작동 됩니다 !

2022-11-07 16:24 UTC, JeongDoYoung2 commented on models/hostDao.js
> +		            host_id,
수정 완료했습니다

2022-11-07 16:25 UTC, JeongDoYoung2 commented on models/hostDao.js
> +    await queryRunner.startTransaction();
넵 수정 완료했습니다.

2022-11-10 06:35 UTC, kyeongraekim approved these changes

2022-11-10 06:35 UTC, merged