[ADD] 예약 데이터 조회
wecode-bootcamp-korea/38-2nd-airB-backend pull request #14
Opened 2022-11-06 05:23 UTC by JeongDoYoung2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 예약 데이터 조회 

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
userId 입력시 해당 유저의 예약 데이터 조회  ( requireLogin 미들웨어가 생기면 전부다 바꿔줄 예정입니다.)

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

## :: 기타 질문 및 특이 사항
-이미지를 배열로 묶어 0번째 index (썸네일사진) 만 보내주려했는데 아직 프론트단에서 이미지 host 구현이 확실하지 않다고 하여 이미지 url이 없는 product도 존재하기때문에  query문 내에서 url들을 배열로 묶어서 맨 앞 사진만 보내는데에 실패했습니다.  

그래서 생각한게 URL이 없는 채로 프론트단에서 데이터를 전송해준다면 DEFAULT 값으로 '이미지 준비중입니다' 라는 사진을 넣어주려했는데 현업에서는 이 문제에 대하여 어떻게 다루는지 궁금합니다.

2022-11-08 07:11 UTC, kyeongraekim requested changes

2022-11-08 07:11 UTC, kyeongraekim commented on routes/reservationRouter.js
> +reservationRouter.get('/:userId', reservationController.getReservationByUserId);
endpoint 설계가 RESTful 하게 작성되어야 합니다."reservation/1" 은 예약 항목의 1번 내용을 의미할 수 있음으로 "reservation/user/1" 의 느낌이 될 수 있게 세부 분기점을 더 명확하게 명시해주세요!

2022-11-08 08:49 UTC, JeongDoYoung2 commented on routes/reservationRouter.js
> +reservationRouter.get('/:userId', reservationController.getReservationByUserId);
수정 완료했습니다 !

2022-11-09 06:59 UTC, kyeongraekim approved these changes
LGTM@~

2022-11-10 01:29 UTC, merged