[ADD] 카카오 소셜 로그인
wecode-bootcamp-korea/38-2nd-airB-backend pull request #15
Opened 2022-11-06 17:55 UTC by Cein1

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 소셜 로그인 API를 사용하여 user 로그인 엔드포인트 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. FE가 user/signin 엔드포인트로 인가 코드(query parameter)를 보냅니다.
2. BE는 인가 코드를 redirect uri로 받아 카카오 서버에 토큰을 요청합니다.
3. 전달받은 토큰으로 사용자 정보를 요청합니다.
4. 전달받은 사용자 정보로 해당 사용자가 서비스에 회원 가입되어 있는지 확인합니다.
5. 가입되지 않았다면 데이터베이스에 회원 가입 처리를, 가입되었다면 전달받은 사용자 정보를 바탕으로 데이터베이스에 회원 정보를 업데이트합니다.
6. 5번이 완료되었다면 FE에게 userId와 hostId가 Payload에 담긴 accessToken을 반환합니다.
7.  6번은 ..utils/auth의 loginRequired 모듈에서 사용됩니다. 숙소예약(userId), 호스팅 페이지(hostId) 접근 권한 부여를 위해 사용될 예정입니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 카카오계정으로 다양한 서비스에 로그인할 수 있도록 하는 카카오 소셜 로그인 API 안내 문서를 읽고 요구사항에 맞추어 application을 구현해 request를 보내고 응답을 받을 수 있게 되었습니다. 
- OAuth 2.0 기반의 소셜 로그인 서비스를 통해 ID 및 비밀번호를 입력받고 검증하는 과정을 직접 구현하지 않고도 사용자에 대한 인증과 인가를 간편하고 안전하게 처리하는 방법을 확인했습니다.
- 브라우저와 node.js에서 사용가능한 Promise 기반 HTTP 클라이언트 라이브러리인 axios를 통해 request를 보내는 방법을 학습했습니다.

<br />

## :: 기타 질문 및 특이 사항
- 없음

2022-11-07 04:43 UTC, kyeongraekim requested changes

2022-11-07 04:43 UTC, kyeongraekim commented on services/userService.js
> +  if (!user) { // saveUserInfo
코드 독해로 의미파악이 가능한 불필요한 주석문은 삭제해주세요~

2022-11-07 04:43 UTC, kyeongraekim commented on utils/auth.js
> +    console.log(user, 'user auth.js단')
불필요한 콘솔로그는 상용 목적의 main으로의 푸시된 코드에서는 꼭 삭제해주세요!

2022-11-07 06:41 UTC, Cein1 commented on services/userService.js
> +  if (!user) { // saveUserInfo
넵 반영 완료하였습니다

2022-11-07 06:41 UTC, Cein1 commented on utils/auth.js
> +    console.log(user, 'user auth.js단')
넵 반영 완료하였습니다

2022-11-08 07:12 UTC, kyeongraekim approved these changes
LGTM!~ API기능은 잘 작동하시는 것 같으나, 실무환경에서는 unittest가 꼭 같이 동봉되어서 올라와야하니다. 유닛테스트에 꼭 도전해주세요!~

2022-11-08 07:12 UTC, merged