[ADD] 메인페이지
wecode-bootcamp-korea/38-2nd-airB-backend pull request #16
Opened 2022-11-07 05:32 UTC by Hey-Hello-World

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-11-08 07:16 UTC, kyeongraekim requested changes

2022-11-08 07:16 UTC, kyeongraekim commented on app.js
> +const appDataSource  = require('./models/dataSource');
이 부분은 의도한 부분이 맞으신지 다시 한 번 확인해주세요!~

2022-11-08 07:16 UTC, kyeongraekim commented on controllers/productController.js
> +    const { lowprice, highprice, bed, bathroom, bedroom, APT, GH, HT, themeId, guest, city, checkIn, checkOut} = req.query;
APT, GH, HT의 명칭등 전반적으로 변수명으로 선언하기에는 다소 모호합니다. 변수명의 정확한 의미를 담을 수 있는 내용으로 바꾸어주세요. 예시) bed -> bedNumber 등

2022-11-08 07:16 UTC, kyeongraekim commented on services/productService.js
> +            }
filter Option이 전체적으로 if-else의 과도한 chianing으로 이루어진 것처럼 보여지네요. 훨씬 경제적이고 가독성 좋은 swtich - case 문으로의 리팩토링에 도전해보세요!

2022-11-08 08:43 UTC, Hey-Hello-World commented on app.js
> +const appDataSource  = require('./models/dataSource');
객체로 감싼 것을 없애는 과정에서 컨벤션 오타가 발생 하였네요 감사합니다 수정 완료 하였습니다.

2022-11-08 10:36 UTC, Hey-Hello-World commented on controllers/productController.js
> +    const { lowprice, highprice, bed, bathroom, bedroom, APT, GH, HT, themeId, guest, city, checkIn, checkOut} = req.query;
감사합니다 수정 완료 하였습니다.

2022-11-09 05:53 UTC, Hey-Hello-World commented on services/productService.js
> +            }
아까 말씀 드린 내용처럼 추후 리팩토링 하는 방향으로 진행하겠습니다 감사합니다

2022-11-09 12:19 UTC, kyeongraekim approved these changes
추후 리팩토링 가이드 안내해드리겠습니다!~

2022-11-09 12:19 UTC, merged