[ ADD ] 상세페이지 예약 요청 API
wecode-bootcamp-korea/38-2nd-airB-backend pull request #9
Opened 2022-11-04 01:48 UTC by JeongDoYoung2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상세페이지 예약요청 API

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. FE 에서 reservation POST 요청시 인원수,userPoint,예약날짜 를 비교하며 유효성 검사를 진행 한 후 모든 유효성 검사를 마치면 reservation table에 데이터가 들어옵니다. 

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 날짜 비교에 대해 자세히 알게 되었습니다.
- 트랜젝션에 대하여 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
-현재 Dao단에 있던 로직들이 기존에는 Service단에 있었다가 옮긴건데, service단에 있어도 되는건지 궁금하고 안된다면 그 이유가 궁금합니다!

2022-11-04 05:16 UTC, kyeongraekim requested changes

2022-11-04 05:16 UTC, kyeongraekim commented on controllers/reservationController.js
> +    res.status(201).json({message : 'COMPLETE RESERVATION!!!'});
반환하는 메세지는 사용자가 아닌 클라이언트/프론트엔드에게 전달하는 메세지입니다. "reservation complete"  정도의 메세지로 불필요한 특수기호 등을 제외하고 수정해주세요
!~

2022-11-04 05:16 UTC, kyeongraekim commented on controllers/reservationController.js
> +        const error = new Error('FAILED RESERVATION...');
이곳도 마찬가지 입니다.

2022-11-04 05:16 UTC, kyeongraekim commented on controllers/reservationController.js
> +
불필요한 공백은 삭제해주세요!~

2022-11-04 05:16 UTC, kyeongraekim commented on models/reservationDao.js
> +            ) VALUE ( ?, ?, ?, ?, ?, 1 )
Reservation Status_id가 현재 숫자 1로 하드 코딩 되어있습니다. status와 같은 특정 상태에 대한 나열은 enum으로 관리하여 가독성을 높여주세요! 아래 예시를 참고해주세요!

``` javascript
const orderStatusEnum = Object.freeze({
     ADDED : 1,
     CANCELED : 2
 });

 module.exports = { orderStatusEnum };

2022-11-04 05:16 UTC, kyeongraekim commented on models/reservationDao.js
> +            throw err;
이곳에서 에러에 대한 메세지 설정 뿐만 아니라 에러 상태코드도 함께 전달해주세요~ 옳지 못한 클라이언트의 요청에 부응하는 상태코드를 포함시켜주세요~

2022-11-04 05:16 UTC, kyeongraekim commented on models/reservationDao.js
> +        for(let i = 0; i< reservationValidate.length; i++){
웹 개발과 같은 실무선의 개발에서는 i, j 와 같은 코테용 변수선언은 최대한 지양해주셔야 합니다. baseNumber 정도의 내용으로 수정해주세요~

2022-11-04 05:16 UTC, kyeongraekim commented on models/reservationDao.js
> +                    const err = {message : '이미 예약이 다 찼습니다.'};
반환되는 에러 메세지는 한글이 아닌 간단한 영문으로 작성해주세요~

2022-11-04 05:16 UTC, kyeongraekim commented on models/reservationDao.js
> +            const err = {message : '정원초과'};
해당 사이트를 방문할 다양한 경우의 케이스가 있을 수 있으니, 반환되는 에러 메세지는 한글이 아닌 간단한 영문으로 작성해주세요~ 전반적으로 다 살펴봐주세요!

2022-11-07 05:00 UTC, kyeongraekim requested changes

2022-11-07 05:00 UTC, kyeongraekim commented on models/reservationDao.js
> +        CANCELED : 2
- 해당 enum만을 모아놓을 수 있는 별도의 폴더/파일에서 따로 관리해주세요. 다른Dao, service등에서도 언제든지 쓰일 수 있기 때문입니다.
- 그리고 Added, Canceled는 제가 예시로 들어드린 상태였는데 현재 프로젝트 기획상 상태가 위와 같이 동일하게 가나요?

2022-11-07 05:00 UTC, kyeongraekim commented on models/reservationDao.js
> +            err.statusCode = 500;
잘못된 요청으로 인해서 비롯된 에러임으로, 500 말고 400으로 변경 해주세요!~

2022-11-07 05:00 UTC, kyeongraekim commented on models/reservationDao.js
> +            INSERT INTO reservations (
Insert의 행위가 다른 시점에서 이루어지기 때문에 transaction이 이곳에서 이루어져야 할것 같네요!~

2022-11-07 05:29 UTC, JeongDoYoung2 commented on models/reservationDao.js
> +        CANCELED : 2
넵 다른파일에서 관리하겠습니다 !
현재 저희 프로젝트 기획상 예약상태는 관리하지 않기때문에 별문제 없었습니다

2022-11-07 05:32 UTC, JeongDoYoung2 commented on models/reservationDao.js
> +            INSERT INTO reservations (
transaction이 완료 된 후에 return 값을 INSERT의 행위가 담겨있는 함수실행으로 지정해줬는데 혹시 문제가 있나요?

2022-11-09 06:58 UTC, kyeongraekim approved these changes
LGTM!~

2022-11-09 06:58 UTC, merged